
spring.datasource.url=jdbc:mysql://localhost:3306/paymentdb
spring.datasource.username=root
spring.datasource.password=720730

server.port=8080

toss.client-key=test_ck_6BYq7GWPVvvpYXJq0dbaVNE5vbo1
toss.secret-key=test_sk_Z61JOxRQVEbEQQ09q5MmrW0X9bAq
app.frontend-url=http://localhost:3000
